### ISSUE TITLE
zSystems und Quantum Computing

### ISSUE THREAD

**Issue by illessa772** [AcademicMainframeConsortium/YTMainframeMeetup#1]
Kurzer Überblick über Quantum Computing (was ist es, wofür kann es verwendet werden, was hat es mit IBM Z zu tun) - ca. 10 Minuten. Sofern die Arbeit nicht dazwischen kommt, kann ich dafür gerne den Dezember-Termin nutzen.

**Comment by skriesch** [comment]
Danke für den Vorschlag!

**Comment by illessa772** [comment]
Nico Einsidler (IBM Wien) dazu einladen

**Comment by skriesch** [comment]
Klappt alles zeitlich? Hat Nico auch kein Problem zu kommen?

**Comment by illessa772** [comment]
Bis jetzt schaut's zeitlich gut aus.
Nico hat leider nicht geantwortet; vielleicht ist er auf Urlaub?

**Comment by skriesch** [comment]
Dann versuche ich ihn nochmals über andere Wege zu erreichen. Aber gut, dass es allgemein klappt.
Ich freue mich schon auf Deinen Vortrag! :)

**Comment by illessa772** [comment]
Für morgen passt alles. Wenn nicht ein Überraschungsflug reinkommt, bin ich da. :-)
Hast du Nico erreicht? Falls nicht, finde ich sollte nicht über seinen Kopf hinweg mit seinem Namen geworben werden...

**Comment by skriesch** [comment]
Ich habe @mgrossmann geschrieben, dass er bitte Nico aus seinem Post raus nehmen soll.

**Comment by illessa772** [comment]
Alles klar, danke dir!

**Comment by mgrossmann** [comment]
Ich hab es wieder rausgenommen.

**Comment by illessa772** [comment]
[IBM zSystems IBM Q Slide Deck YTMC.pdf](https://github.com/AcademicMainframeConsortium/YTMainframeMeetup/files/10459958/IBM.zSystems.IBM.Q.Slide.Deck.YTMC.pdf)

**Comment by zOrphanBlack** [comment]
Hi ihr,
hab mich gerade angelegt im GitHub --> Tobias

Lese gerade diesen Artikel:
https://www.spektrum.de/news/ist-die-digitale-privatsphaere-schon-heute-gefaehrdet/2098500?utm_source=pocket-newtab-global-de-DE

Lustig diese eine Aussage dazu: »Alles in allem ist dies eine der irreführendsten Arbeiten über Quantencomputer, die ich in den letzten 25 Jahren gesehen habe« (Scott Aaronson, Quantencomputer-Theoretiker an der University of Texas)

**Comment by skriesch** [comment]
Danke für den Vortrag, @illessa772! Zur besseren Übersichtlichkeit habe ich deine Folien jetzt im Projekt committet. So kann man auch besser auf die vorherigen Vorträge in der Zukunft zurückgreifen.

@zOrphanBlack Hast Du Lust auch einen Vortrag zu halten? Dann kannst Du gerne einen Issue dazu öffnen. Natürlich sind auch Recherche/Forschungsthemen aus den USA willkommen.
