### ISSUE TITLE
Gegenseitiges Kennenlernen und Erfahrungsaustausch mit den zTalents 

### ISSUE THREAD

**Issue by illessa772** [AcademicMainframeConsortium/YTMainframeMeetup#11]
zTalents CH: https://www.gse.org/swiss-workinggroups/ztalents-ch/

**Comment by skriesch** [comment]
Wie wäre es die unterschiedlichen zTalents Gruppen einzuladen?

> GSE zTalents DE: https://www.gse.org/german-workinggroups/mu30d-ztalents/ (David fragen)
> DATEV zTalents: https://www.datev-karriereblog.de/author/redakteur_ztalents/ (Walter fragen)

**Comment by illessa772** [comment]
Gute Idee! Dann stelle ich mal den Kontakt mit den zTalents CH her und lade sie für den 21.03. ein.

**Comment by skriesch** [comment]
Ich lade die anderen ein.

**Comment by illessa772** [comment]
[IBM Global Skills Accelerator and EnergiZ @ IBM DACH - YTMC_20240321.pdf](https://github.com/AcademicMainframeConsortium/YTMainframeMeetup/files/14748193/IBM.Global.Skills.Accelerator.and.EnergiZ.%40.IBM.DACH.-.YTMC_20240321.pdf)
Vielen Dank an Tim McKeoun und André Spahni von IBM Schweiz für ein Kennenlernen der zTalents CH und einer Präsentation des IBM Skills Accelerator Programms und EnergiZ @ IBM DACH!

**Comment by skriesch** [comment]
Kannst Du das PDF bitte committen? So ist es nicht mehr zugänglich.

**Comment by illessa772** [comment]
Wie/wo mache ich das?

**Comment by skriesch** [comment]
git clone https://github.com/AcademicMainframeConsortium/YTMainframeMeetup.git #Ein Clone vom Verzeichnis dieses Projekts
Verzeichnis mit Datum anlegen #Jedes Meetup wird mit Verzeichnis angelegt als gute Struktur
Dort die Datei von oben hinzufügen #Jede Präsentation ist dann sortiert nach Datum
git add IBM_Global_Skills* #Git-Befehl, damit die Datei im Verzeichnis erkannt wird
git commit -m "zTalents Vortrag"  #Commit-Message, was in Github neben der Datei und dem Verzeichnis dann angezeigt wird
git push #Daten an Github senden (Du hast hier Admin-Rechte)

**Comment by illessa772** [comment]
Das waren gerade meine ersten Versuche mit Github. Soweit ich sehen kann, schaut es gut aus. Schau aber bitte nochmal drüber, ob alles passt. Danke dir!

**Comment by skriesch** [comment]
Sieht gut aus.

Eine kleine Ergänzung für die Zukunft. Bei der Commit-Message kann man auch noch Referenzen zu den Issues hinzufügen. Das geht dann mit #11 als Beispiel für diesen Issue.

Git ist zur Versionsverwaltung in Kombination mit Github/Gitlab eine Grundlagenqualifikation der Informatik, die auch in jedem Unternehmen eingesetzt wird. Eigentlich wird das auch als Teil eines Informatik-Studiums gesehen. Mein Professor der Bachelorarbeit hätte sich gefreut, wenn er meine Software auf einem USB-Stick oder per E-Mail bekommen hätte...

Auch an der Uni wird bei uns in den Übungsaufgaben damit gearbeitet, damit man realitätsnah an die Softwareentwicklung herangeführt wird.

**Comment by illessa772** [comment]
Super, danke dir!

Da ich im Bachelor keine Projektarbeit verfasst habe und meine Abschlussarbeit keinen praktischen Teil hatte, bin ich damit leider nie in Berührung gekommen. Und zu meiner Programmierer-Zeit gab es noch kein Git. Umso besser da jetzt etwas reinschnuppern zu können. Danke für die Hilfestellung!
