### ISSUE TITLE
IBM zSystems Emulationen mit Container Anwendungen

### ISSUE THREAD

**Issue by skriesch** [AcademicMainframeConsortium/YTMainframeMeetup#2]
Ich habe meine Bachelorarbeit über "Enablement of Kubernetes based open source projects on IBM Z" geschrieben.
Es ging um Emulationen mit integrierten Anwendungs-Containern, die man in die CI/CD Pipelines integrieren oder auf dem Laptop (als Tests in der Entwicklungsumgebung) laufen lassen kann. Das soll bei einem Meetup auch vorgestellt werden.

**Comment by mgrossmann** [comment]
Klingt nach einem spannenden Thema. 
+1 von mir

**Comment by mgrossmann** [comment]
Danke für deinen Vortrag, @skriesch 

Hast du evtl. noch Unterlagen, die du mit uns teilen möchtest?

Lieben Gruß Mike
