### ISSUE TITLE
Cobol - Eine (ganz) kurze Einführung

### ISSUE THREAD

**Issue by mgrossmann** [AcademicMainframeConsortium/YTMainframeMeetup#4]
Am 16.03.2023 steht unser nächstes Meetup an.

Das Thema wird Cobol sein. @skriesch Hat sich angeboten die Programmiersprache 
kurz und knapp, inklusives eines kleinen Hello Worlds, vorzustellen.

Vielen Dank dafür. 

Gerne würde ich auch dich @zOrphanBlack einladen.
Vielleicht hättest du ja Zeit und Lust auch zum Thema etwas zu erzählen?

@ErnstLugert ich würde mich sehr freuen, wenn du die Einladungen versenden könntest.
Ich weiss, wir sind sehr spät dran. Sorry dafür.

Gruß Mike

**Comment by skriesch** [comment]
Folien sind committet.
